# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jw < Formula
  desc "A CLI tool to monitor Jenkins jobs"
  homepage "https://github.com/baggiiiie/jw"
  version "0.0.4"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/baggiiiie/jw/releases/download/v0.0.4/jw_Darwin_x86_64.tar.gz"
    sha256 "ca39e8c981730951f9164d130aa19b568307894c36587ff25d1959dad1adfdd7"

    def install
      bin.install "jw"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/baggiiiie/jw/releases/download/v0.0.4/jw_Darwin_arm64.tar.gz"
    sha256 "dcaa5610f438337358a7325cf0e0e0bc03003d06341aed6fd2ef94773f5ff484"

    def install
      bin.install "jw"
    end
  end
end
