# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jw < Formula
  desc "A CLI tool to monitor Jenkins jobs"
  homepage "https://github.com/baggiiiie/jw"
  version "0.0.5"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/baggiiiie/jw/releases/download/v0.0.5/jw_Darwin_x86_64.tar.gz"
    sha256 "0cc4b6b5fd4caee72f2eb65ffd3abe5863795f61a5f0f14161014e9dc58d813d"

    define_method(:install) do
      bin.install "jw"
      (share/"jw"/"extension").install Dir["extension/*"]
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/baggiiiie/jw/releases/download/v0.0.5/jw_Darwin_arm64.tar.gz"
    sha256 "754ca518744f13bd2bcfb0af5f91296df2ece4e9280b43cb21253c85b4d5049d"

    define_method(:install) do
      bin.install "jw"
      (share/"jw"/"extension").install Dir["extension/*"]
    end
  end

  def caveats
    <<~EOS
      To install the Chrome extension:
        1. Open chrome://extensions
        2. Enable "Developer mode"
        3. Click "Load unpacked" and select:
           #{share}/jw/extension
    EOS
  end
end
